// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremblantLifecycle.Api.Data;

#nullable disable

namespace TremblantLifecycle.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804182656_ReplaceBesoinCodeAlarmeWithDetailsText")]
    partial class ReplaceBesoinCodeAlarmeWithDetailsText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("RequestNumberSeq");

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AccessDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("BadgeZones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeAlarmeDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stationnement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("AccessDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("AutreLogiciel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("ApplicationsDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttachmentId");

                    b.HasIndex("RequestId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("EquipmentDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingConfidentialComment", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommentaireRH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OffboardingConfidentialComments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommentairesIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesParkingAcces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesRedingote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DerniereJournee")
                        .HasColumnType("date");

                    b.Property<string>("DetailsRaison")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndemniteVacances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisonArret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reembaucheriez")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OffboardingDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OnboardingDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateEntreePrevue")
                        .HasColumnType("date");

                    b.Property<string>("RegleDePaye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegleDePayeCommentaire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OnboardingDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessPos", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestAccessPos");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessSysteme", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestAccessSystemes");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestApplication", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestApplications");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEmployee", b =>
                {
                    b.Property<int>("RequestEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestEmployeeId"));

                    b.Property<string>("CodeEmploiSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartementSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GestionnaireSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("TypeEmploiSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkdayEmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestEmployeeId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestEmployees");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEquipment", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestEquipments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AccessDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("AccessDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.AccessDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("ApplicationsDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Attachment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("EquipmentDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingConfidentialComment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("ConfidentialComment")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OffboardingConfidentialComment", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("OffboardingDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OffboardingDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OnboardingDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("OnboardingDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OnboardingDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessPos", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.AccessDetail", null)
                        .WithMany("PosHebergement")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessSysteme", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.AccessDetail", null)
                        .WithMany("Systemes")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestApplication", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", null)
                        .WithMany("Applications")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEmployee", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithMany("Employees")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEquipment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", null)
                        .WithMany("Equipements")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AccessDetail", b =>
                {
                    b.Navigation("PosHebergement");

                    b.Navigation("Systemes");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Request", b =>
                {
                    b.Navigation("AccessDetail");

                    b.Navigation("ApplicationsDetail");

                    b.Navigation("Attachments");

                    b.Navigation("ConfidentialComment");

                    b.Navigation("Employees");

                    b.Navigation("EquipmentDetail");

                    b.Navigation("OffboardingDetail");

                    b.Navigation("OnboardingDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
