// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TremblantLifecycle.Api.Data;

#nullable disable

namespace TremblantLifecycle.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821195134_AddOnboardingDepartmentComments")]
    partial class AddOnboardingDepartmentComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("RequestNumberSeq");

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AccessDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("BadgeZones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeAlarmeDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stationnement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("AccessDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AppUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("AutreLogiciel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("ApplicationsDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedByObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttachmentId");

                    b.HasIndex("RequestId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.D365JobCodeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalLegalEntities")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApAccessDetails")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("ApprovalLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DepartmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobTitleEnglish")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LegalEntity")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LevyEmployee")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("JobCode")
                        .IsUnique();

                    b.ToTable("D365JobCodeTemplates");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.D365JobCodeTemplateRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("D365JobCodeTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("D365JobCodeTemplateId", "Role")
                        .IsUnique();

                    b.ToTable("D365JobCodeTemplateRoles");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.D365SecurityRoleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("JobCode", "Role")
                        .IsUnique();

                    b.ToTable("D365SecurityRoleMappings");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.D365UserSecurityRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JobCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PositionTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurityRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("D365UserSecurityRoles");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.DynawayUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PersonnelNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Login");

                    b.ToTable("DynawayUsers");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("EquipmentDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingConfidentialComment", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommentaireRH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OffboardingConfidentialComments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommentairesIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesPuceAcces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesRedingote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesStationnement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateRetourConnue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateRetourTravail")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DerniereJournee")
                        .HasColumnType("date");

                    b.Property<string>("DetailsRaison")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndemniteVacances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotifNonAdmissibilite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreavisRecu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaisonArret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reembaucheriez")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OffboardingDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OnboardingConfidentialComment", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommentaireRH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByObjectId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OnboardingConfidentialComments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OnboardingDetail", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("CommentairesIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesPuceAcces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesRedingote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairesStationnement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateEntreePrevue")
                        .HasColumnType("date");

                    b.Property<string>("RegleDePaye")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegleDePayeCommentaire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("OnboardingDetails");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId");

                    b.HasIndex("RequestNumber")
                        .IsUnique();

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessPos", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestAccessPos");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessSysteme", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestAccessSystemes");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestApplication", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestApplications");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEmployee", b =>
                {
                    b.Property<int>("RequestEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestEmployeeId"));

                    b.Property<string>("CodeEmploiSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartementSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GestionnaireSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("TypeEmploiSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkdayEmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequestEmployeeId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestEmployees");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEquipment", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RequestId", "Value");

                    b.ToTable("RequestEquipments");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.TicketTemplate", b =>
                {
                    b.Property<int>("TicketTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketTemplateId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TicketTemplateId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("TicketTemplates");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AccessDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("AccessDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.AccessDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("ApplicationsDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Attachment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.D365JobCodeTemplateRole", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.D365JobCodeTemplate", "D365JobCodeTemplate")
                        .WithMany("Roles")
                        .HasForeignKey("D365JobCodeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("D365JobCodeTemplate");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("EquipmentDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingConfidentialComment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("ConfidentialComment")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OffboardingConfidentialComment", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OffboardingDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("OffboardingDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OffboardingDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OnboardingConfidentialComment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("OnboardingConfidentialComment")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OnboardingConfidentialComment", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.OnboardingDetail", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithOne("OnboardingDetail")
                        .HasForeignKey("TremblantLifecycle.Api.Models.Entities.OnboardingDetail", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessPos", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.AccessDetail", null)
                        .WithMany("PosHebergement")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestAccessSysteme", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.AccessDetail", null)
                        .WithMany("Systemes")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestApplication", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", null)
                        .WithMany("Applications")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEmployee", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.Request", "Request")
                        .WithMany("Employees")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.RequestEquipment", b =>
                {
                    b.HasOne("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", null)
                        .WithMany("Equipements")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.AccessDetail", b =>
                {
                    b.Navigation("PosHebergement");

                    b.Navigation("Systemes");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.ApplicationsDetail", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.D365JobCodeTemplate", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.EquipmentDetail", b =>
                {
                    b.Navigation("Equipements");
                });

            modelBuilder.Entity("TremblantLifecycle.Api.Models.Entities.Request", b =>
                {
                    b.Navigation("AccessDetail");

                    b.Navigation("ApplicationsDetail");

                    b.Navigation("Attachments");

                    b.Navigation("ConfidentialComment");

                    b.Navigation("Employees");

                    b.Navigation("EquipmentDetail");

                    b.Navigation("OffboardingDetail");

                    b.Navigation("OnboardingConfidentialComment");

                    b.Navigation("OnboardingDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
